-- lua/config/icons.lua
-- Enhanced icons using Nerd Fonts

return {
  diagnostics = {
    Error = "", -- nf-fa-times_circle
    Warn = "", -- nf-fa-exclamation_triangle
    Hint = "", -- nf-fa-lightbulb_o
    Info = "", -- nf-fa-info_circle
  },
  git = {
    added = "", -- nf-oct-diff_added
    modified = "", -- nf-oct-diff_modified
    removed = "", -- nf-oct-diff_removed
    branch = "", -- nf-dev-git_branch
    unstaged = "󰄱", -- nf-md-source_branch_sync
    staged = "", -- nf-oct-git_pull_request
    unmerged = "", -- nf-oct-git_compare
    renamed = "󰁕", -- nf-md-rename_box
    untracked = "", -- nf-fa-question
  },
  kinds = {
    Array = "", -- nf-fa-list_alt
    Boolean = "⊨", -- nf-fa-toggle_on
    Class = "", -- nf-fa-cube
    Color = "", -- nf-fa-paint_brush
    Constant = "", -- nf-fa-square
    Constructor = "", -- nf-fa-building
    Enum = "練", -- nf-fa-list_ul
    EnumMember = "", -- nf-fa-list
    Event = "", -- nf-fa-bolt
    Field = "", -- nf-fa-certificate
    File = "", -- nf-fa-file
    Folder = "", -- nf-fa-folder
    Function = "", -- nf-fa-code
    Interface = "", -- nf-fa-share_alt
    Key = "", -- nf-fa-key
    Keyword = "", -- nf-fa-key
    Method = "ƒ", -- nf-fa-flask
    Module = "", -- nf-fa-cubes
    Namespace = "", -- nf-fa-globe
    Null = "󰟢", -- nf-md-null
    Number = "", -- nf-fa-hashtag
    Object = "", -- nf-fa-dot_circle_o
    Operator = "", -- nf-fa-calculator
    Package = "", -- nf-fa-archive
    Property = "", -- nf-fa-wrench
    Reference = "", -- nf-fa-bookmark
    Snippet = "", -- nf-fa-puzzle_piece
    String = "", -- nf-fa-quote_right
    Struct = "", -- nf-fa-object_group
    Text = "", -- nf-fa-align_left
    TypeParameter = "", -- nf-fa-cogs
    Unit = "塞", -- nf-fa-check_square
    Value = "", -- nf-fa-tag
    Variable = "", -- nf-fa-asterisk
  },
  ui = {
    ArrowCircleDown = "", -- nf-fa-arrow_circle_down
    ArrowCircleLeft = "", -- nf-fa-arrow_circle_left
    ArrowCircleRight = "", -- nf-fa-arrow_circle_right
    ArrowCircleUp = "", -- nf-fa-arrow_circle_up
    BoldArrowDown = "", -- nf-fa-arrow_down
    BoldArrowLeft = "", -- nf-fa-arrow_left
    BoldArrowRight = "", -- nf-fa-arrow_right
    BoldArrowUp = "", -- nf-fa-arrow_up
    BoldClose = "", -- nf-fa-close
    BoldDividerLeft = "«", -- nf-fa-angle_double_left
    BoldDividerRight = "»", -- nf-fa-angle_double_right
    BoldLineLeft = "▎", -- Left vertical line (box drawing)
    BookMark = "", -- nf-fa-bookmark
    BoxChecked = "", -- nf-fa-check_square_o
    Bug = "", -- nf-fa-bug
    Calendar = "", -- nf-fa-calendar
    Check = "✔", -- nf-fa-check
    ChevronRight = "", -- nf-fa-chevron_right
    ChevronShortDown = "", -- nf-fa-chevron_down
    ChevronShortLeft = "", -- nf-fa-chevron_left
    ChevronShortRight = "", -- nf-fa-chevron_right
    ChevronShortUp = "", -- nf-fa-chevron_up
    Circle = "", -- nf-fa-circle_o
    Close = "󰅖", -- nf-md-close
    CloudDownload = "", -- nf-fa-cloud_download
    Code = "", -- nf-fa-code
    Comment = "", -- nf-fa-comment
    Dashboard = "", -- nf-fa-dashboard
    DebugConsole = "", -- nf-fa-terminal
    DividerLeft = "", -- nf-fa-angle_left
    DividerRight = "", -- nf-fa-angle_right
    DoubleChevronRight = "»", -- Double right chevron
    Ellipsis = "…", -- nf-fa-ellipsis_h
    EmptyFolder = "", -- nf-fa-folder_o
    EmptyFolderOpen = "", -- nf-fa-folder_open_o
    File = "", -- nf-fa-file
    FileSymlink = "", -- nf-fa-file_o
    Files = "", -- nf-fa-files_o
    FindFile = "", -- nf-fa-search
    FindText = "", -- nf-fa-search_plus
    Fire = "", -- nf-fa-fire
    Folder = "", -- nf-fa-folder
    FolderOpen = "", -- nf-fa-folder_open
    FolderSymlink = "", -- nf-fa-folder_o
    Forward = "", -- nf-fa-forward
    Gear = "", -- nf-fa-gear
    History = "", -- nf-fa-history
    Lightbulb = "", -- nf-fa-lightbulb_o
    LineLeft = "▏", -- Left vertical line (box drawing)
    LineMiddle = "│", -- Middle vertical line (box drawing)
    List = "", -- nf-fa-list
    Lock = "", -- nf-fa-lock
    NewFile = "", -- nf-fa-file_o
    Note = "", -- nf-fa-sticky_note
    Package = "", -- nf-fa-archive
    Pencil = "", -- nf-fa-pencil
    Plus = "", -- nf-fa-plus
    Project = "", -- nf-fa-briefcase
    Search = "", -- nf-fa-search
    SignIn = "", -- nf-fa-sign_in
    SignOut = "", -- nf-fa-sign_out
    Tab = "", -- nf-fa-tablet
    Table = "", -- nf-fa-table
    Target = "󰀘", -- nf-md-target
    Telescope = "🔭", -- nf-fa-telescope
    Text = "", -- nf-fa-file_text
    Tree = "", -- nf-fa-tree
  }
}

